name: Lint Pushed Code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.4
    - name: Lint with Ruff
      id: lint
      run: |
        make lint