name: Descriptive Statistics Project Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.4
    - name: Install dependencies
      id: install
      run: |
        make install
    - name: Lint with Ruff
      id: lint
      run: |
        make lint
    - name: Test
      id: test
      run: |
        make test
    - name: Format code
      id: format
      run: |
        make format 
        
    
